---
title: "Untitled"
output: html_document
date: "2024-11-13"
---

```{r setup, include=FALSE}
# packages that will be used
library(sf)
library(terra) 
library(ggplot2)
library(dplyr)
library(ggspatial)
library(tmap)
library(RColorBrewer)
library(raster)
```





```{r - Random stuff that may be useful later}
#gdb_file <- "C:/Users/Admin/Downloads/OR_DEM_10M.gdb/OR_DEM_10M.gdb/a00000029.gdbtable"
#layers <- st_layers(gdb_file)
#print(layers)

#gdb_data <- st_read(dsn = gdb_file, layer = "fras_blk_DEM_10meter_Oregon")


#head(gdb_data)

# commented code below is for cropping the extent of the data, will show a smaller portion of the state rather than a reduced res version

#extent <- ext(dem_rast) * 0.01  # Crop to 1% of the original size
#dem_rast_subset <- crop(dem_rast, extent)

# Convert the subset to a data frame
#dem_rast_df <- as.data.frame(dem_rast_subset, xy = TRUE)
#dem_rast_df <- as.data.frame(dem_rast, xy = TRUE)
#dem_rast_df

#gdb_path <- "C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb"
#raster <- rast("C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb")
#raster
#layers <- terra::sources(gdb_path)


#crs(ecoregions_OR, proj=TRUE)
#crs(OBA_sf)
#crs(dem_rast_downsampled, proj = TRUE)

#crs("EPSG:4326")

# current_bbox <- st_bbox(bee_species_sp)
# print(current_bbox)
# 
# # Defining a new bounding box
# new_bbox <- st_bbox(c(xmin = -123.414, ymin = 41.998, xmax = -117.227, ymax = 45.868), crs = st_crs(bee_species_sp))
# 
# # Cropping to the new bounding box
# bee_data_cropped <- st_crop(bee_species_sp, new_bbox)
# 
# print(st_bbox(bee_data_cropped))

#cat(sort(unique(OBA_clean$Latitude)))
#cat(sort(unique(OBA_clean$Longitude))
```





```{r - Code for reading in a reducing resolution of DEM data}

describe("C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb")
dem_rast <- rast("C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb")
dem_rast

dem_rast_downsampled <- aggregate(dem_rast, fact = 100, fun = mean)
dem_rast_dsamp_df <- as.data.frame(dem_rast_downsampled, xy = TRUE)

head(dem_rast_dsamp_df)
summary(values(dem_rast_downsampled))

```




```{r Reading in ecoregion data and plot of elevation and ecoregions}

ecoregions_vec <- st_read("C:/Users/Admin/Downloads/ds-environ-JS/5-lab-OR-fires/5-OR-fires/OR-ecoregions/Ecoregions_OregonConservationStrategy.shp")
head(ecoregions_vec)

crs(ecoregions_vec, proj = TRUE)
crs(dem_rast_downsampled, proj = TRUE)

# changing ecoregion crs to dem crs
ecoregions <- st_transform(ecoregions_vec, crs(dem_rast))


elevation_all_ecoregions_plot <- ggplot() +
  geom_raster(data = dem_rast_dsamp_df, aes(x = x, y = y, fill = OR_DEM_10M_files)) +
  scale_fill_viridis_c() +
  geom_sf(data = ecoregions, color = "white", fill = NA) 

elevation_all_ecoregions_plot

```

```{r getting rid of na values and cleaning coordinates to only OR entries}

OBA <- read.csv("C:/Users/Admin/Downloads/ds-environ-JS/6_lab_OBA_spatial/6_OBA_spatial/OBA_2018-2023.csv")
head(OBA)
names(OBA)

OBA_filtered <- OBA %>% 
  dplyr::select("Dec..Lat." , "Dec..Long.", "Species", "State") %>%
  rename(Latitude = Dec..Lat., Longitude = Dec..Long.) %>%
  filter(!is.na(Species) & Species != "") %>%
  dplyr::select("Latitude" , "Longitude", "Species", "State")

OBA_filtered


head(OBA_filtered)

OBA_clean <- OBA_filtered %>%
  filter(!is.na(Longitude) & !is.na(Latitude)) %>%
  filter(Longitude > -125 & Longitude < -116.5 & Latitude > -47 & Latitude < 47) %>%
  filter(Latitude != 39.98700) %>%
  filter(Latitude != 46.99) %>%
  filter(Longitude != -125.3831) %>%
  filter(Latitude != 41.680) %>%
  filter(Longitude != -116.464) %>%
  filter(State %in% c("Oregon ", "Oregon", "OR"))

head(OBA_clean)

OBA_sf <- st_as_sf(OBA_clean,
                          coords = c("Longitude","Latitude"),
                          crs = crs("EPSG:4326"))
head(OBA_sf)

OBA_sf

OBA_reprojected <- st_transform(OBA_sf, crs(dem_rast))

class(OBA_reprojected)

```

```{r Filling out OBA df with elevation and ecoregion for each bee observation}

# basically adding elevation column to oba data
OBA_reprojected$Elevation <- terra::extract(dem_rast_downsampled, OBA_reprojected, ID = FALSE)[[1]]

hist(OBA_reprojected$Elevation)


# adding ecoregion column to oba data
template <- rast(vect(ecoregions), res = res(dem_rast_downsampled))

rast_ecoregions <- rasterize(vect(ecoregions), template, field = "Ecoregion")

OBA_reprojected$Ecoregion <- terra::extract(rast_ecoregions, OBA_reprojected, ID = FALSE)[[1]]

OBA_reprojected
plot(rast_ecoregions)
table(OBA_reprojected$Ecoregion)


# turning reprojected OBA data into df
OBA_reprojected_df <- as.data.frame(OBA_reprojected, xy=TRUE)
class(OBA_reprojected_df)


# adding in elevation bins - seems like this method doesn't work quite right
# since the border issues cause the ecoregions touching the edge of the 
# OBA_reprojected_df <- OBA_reprojected_df %>%
#   group_by(Ecoregion) %>%
#   mutate(
#     ElevationBin = cut(
#       Elevation, 
#       breaks = seq(min(Elevation), max(Elevation), length.out = 11), include.lowest = TRUE))


# this binning method works but sometimes gives 11 bins instead of 10 
OBA_reprojected_wBreaks <- OBA_reprojected %>%
  group_by(Ecoregion) %>%
  mutate(
    ElevationBin = cut(
      Elevation, 
      breaks = 4,
      include.lowest = TRUE))

OBA_reprojected_wBreaks <- as.data.frame(OBA_reprojected_wBreaks)




# Get unique ecoregions with NA ElevationBin
unique_ecoregions_with_na <- unique(na_rows$Ecoregion)

# Display the ecoregions
table(unique_ecoregions_with_na)
 
# removing NA elevation bins
OBA_reprojected_wBreaks_clean <- OBA_reprojected_wBreaks %>%
  filter(!is.na(ElevationBin)) %>% 
  filter(!is.na(Ecoregion)) %>% 
  filter(Ecoregion != "Nearshore")



# Check the cleaned dataset
(OBA_reprojected_wBreaks_clean)

sum(is.na(OBA_reprojected_wBreaks_clean$ElevationBin))

length(unique(OBA_reprojected_wBreaks_clean$ElevationBin[OBA_reprojected_wBreaks_clean$Ecoregion == "Nearshore"]))

range(OBA_reprojected_wBreaks_clean$Elevation)

levels(ElevationBin)

# shuffle elevation bins - identity of species varies randomly
# take observed # of species in elevation bin and subtract generated #
# tvd is sum abs(obs - expected) /2 

#shuffle elevation bins

# splits data into separate ecoregions

OBA_reprojected_wBreaks_clean$Ecoregion <- as.character(OBA_reprojected_wBreaks_clean$Ecoregion)
sp_occ <- split(OBA_reprojected_wBreaks_clean, OBA_reprojected_wBreaks_clean$Ecoregion)
shuffled_sp_occ <- list()
for(i in 1:length(sp_occ)){
 shuffled_column <-sample(sp_occ[[i]]$ElevationBin, nrow(sp_occ[[i]]), replace = FALSE)
 new_sp_occ <- sp_occ[[i]]
 new_sp_occ$shuffled_ElevationBin <- shuffled_column
 shuffled_sp_occ[[i]] <- new_sp_occ
}

calc_tvd <- function(observed, null) {

  observed_dist <- observed / sum(observed) 
  null_dist <- null / sum(null)             
  tvd <- 0.5 * sum(abs(observed_dist - null_dist))
  return(tvd)
}

totalV <- list()

for(i in 1:length(shuffled_sp_occ)){
  observed_richness <- shuffled_sp_occ[[i]] %>%
  group_by(ElevationBin) %>%
  summarize(
    BeeSpeciesRichness = length(unique(Species)))
  
  generated_richness <- shuffled_sp_occ[[i]] %>%
  group_by(shuffled_ElevationBin) %>%
  summarize(
    shuffled_BeeSpeciesRichness = length(unique(Species)))
  colnames(generated_richness) <- c("ElevationBin", "shuffled_BeeSpeciesRichness")
  total_richness <- left_join(observed_richness, generated_richness)
 
  totalV[[i]] <- calc_tvd(total_richness$BeeSpeciesRichness,total_richness$shuffled_BeeSpeciesRichness)
  
}

names(totalV) <- names(shuffled_sp_occ)
# makes TVD values a vector
unlist(totalV, recursive = FALSE)


names(total_richness) <- names(shuffled_sp_occ)
total_richness["Willamette Valley"]


names(shuffled_sp_occ) <- names(sp_occ)
# df for each ecoregion - has shuffled and normal elevation bins
shuffled_sp_occ
shuffled_sp_occ[["Coast Range"]]
sp_occ[["Nearshore"]]
names(shuffled_sp_occ)

shuffled_Elevation <- sample(OBA_reprojected_wBreaks_clean$ElevationBin, nrow(OBA_reprojected_wBreaks_clean), replace = FALSE)
OBA_reprojected_wBreaks_clean$shuffled_ElevationBin <- shuffled_Elevation

OBA_reprojected_wBreaks_clean



```

```{r}

Elevation_Richness <- sp_occ %>%
  group_by(ElevationBin, Ecoregion) %>%
  summarize(
    BeeSpeciesRichness= length(unique(Species)))



shuffled_Elevation_Richness <- shuffled_sp_occ %>%
  group_by(shuffled_ElevationBin, Ecoregion) %>%
  summarize(
    BeeSpeciesRichness= length(unique(Species)))

Elevation_Richness

shuffled_Elevation_Richness


```


```{r Setting up TVD code}

# Function to calculate Total Variation Distance
calc_tvd <- function(observed, null) {
  observed_dist <- observed / sum(observed) 
  null_dist <- null / sum(null)             
  tvd <- 0.5 * sum(abs(observed_dist - null_dist))
  return(tvd)
}

# finding the observed tvd of each ecoregion
compute_observed_tvd <- function(Elevation_Richness){
  Elevation_Richness %>%
    group_by(Ecoregion) %>%
    summarize(observed_tvd = calc_tvd(BeeSpeciesRichness, rep(1, length(BeeSpeciesRichness))))
}

  
compute_observed_tvd(Elevation_Richness)
#   
# 
# observed_tvd

```

```{r TVD code continued}

compute_null_tvd <- function(Elevation_Richness) {
  Elevation_Richness %>%
    group_by(Ecoregion) %>%
    reframe(
      null_tvd = calc_tvd(
        sample(BeeSpeciesRichness),  # Shuffle richness values
        rep(1, length(BeeSpeciesRichness))  # Uniform distribution
      ))
    
}

compute_observed_tvd(Elevation_Richness)
compute_null_tvd(Elevation_Richness)
# null doesn't work !!!

combine_tvd_results <- function(Elevation_Richness, num_permutations = 1000) {
  observed <- compute_observed_tvd(Elevation_Richness)
  null <- compute_null_tvd(Elevation_Richness, num_permutations)
  
  # Combine observed and null into a single data frame
  combined <- observed %>%
    left_join(null, by = "Ecoregion")  # Match by Ecoregion
  
  return(combined)
}

# Observed TVD
observed_tvd <- compute_observed_tvd(Elevation_Richness)
observed_tvd
# Null Distribution
null_tvd <- compute_null_tvd(Elevation_Richness, num_permutations = 1000)

# Combine Results
combined_tvd <- combine_tvd_results(Elevation_Richness, num_permutations = 1000)

# View Results
print(combined_tvd)







  # Generating null distributions by shuffling elevation bins
generate_null_distribution <- function(Elevation_Richness, num_permutations = 1000) {
  null_tvd_list <- list()
  
  for (ecoregion in unique(Elevation_Richness$Ecoregion)) {
    sub_data <- Elevation_Richness %>% filter(ecoregion == Ecoregion)
    null_tvds <- numeric(num_permutations)
    
    for (i in 1:num_permutations) {
      shuffled_bins <- sample(sub_data$ElevationBin)
      shuffled_data <- sub_data %>%
        mutate(shuffled_ElevationBin = shuffled_bins) %>%
        group_by(shuffled_ElevationBin) %>%
        summarise(total_richness = sum(richness), .groups = "drop")
      
      null_tvds[i] <- calc_tvd(
        observed = shuffled_data$total_richness,
        null = rep(1, nrow(shuffled_data))
      )
    }
    
    null_tvd_list[[ecoregion]] <- null_tvds
  }
  
  return(null_tvd_list)
}

null_distributions <- generate_null_distribution(data)

# Step 3: Compare observed TVD to null distributions
compare_tvd <- function(observed_tvd, null_distributions) {
  results <- data.frame(ecoregion = integer(), observed_tvd = numeric(), p_value = numeric())
  
  for (ecoregion in names(null_distributions)) {
    null_tvds <- null_distributions[[ecoregion]]
    observed <- observed_tvd %>% filter(ecoregion == as.numeric(ecoregion)) %>% pull(observed_tvd)
    
    # Calculate p-value
    p_value <- mean(null_tvds >= observed)
    
    results <- rbind(results, data.frame(
      ecoregion = as.numeric(ecoregion),
      observed_tvd = observed,
      p_value = p_value
    ))
  }
  
  return(results)
}

results <- compare_tvd(observed_tvd, null_distributions)

# Step 4: Print results
print(results)

```




```{r}

# trying to figure out elevation binning issue

coast_range_data <- OBA_reprojected_wBreaks %>%
  filter(Ecoregion == "Coast Range")

# View the filtered data
print(coast_range_data)
unique(OBA_reprojected_wBreaks$Ecoregion)
sum(is.na(OBA_reprojected_wBreaks$Ecoregion))
 
as.data.frame(OBA_reprojected[is.na(OBA_reprojected$Ecoregion), ])

print(unique(OBA_reprojected_wBreaks$ElevationBin[OBA_reprojected_wBreaks$Ecoregion == "Columbia Plateau"]))


```









```{r Filling out OBA df with elevation and ecoregion for each bee observation}

# basically adding elevation column to oba data
OBA_reprojected$Elevation <- terra::extract(dem_rast_downsampled, OBA_reprojected, ID = FALSE)[[1]]

hist(OBA_reprojected$Elevation)


# adding ecoregion column to oba data
template <- rast(vect(ecoregions), res = res(dem_rast_downsampled))

rast_ecoregions <- rasterize(vect(ecoregions), template, field = "Ecoregion")

OBA_reprojected$Ecoregion <- terra::extract(rast_ecoregions, OBA_reprojected, ID = FALSE)[[1]]

plot(rast_ecoregions)
table(OBA_reprojected$Ecoregion)


# turning reprojected OBA data into df
OBA_reprojected_df <- as.data.frame(OBA_reprojected, xy=TRUE)



# adding in elevation bins - seems like this method doesn't work quite right
# since the border issues cause the ecoregions touching the edge of the 
# OBA_reprojected_df <- OBA_reprojected_df %>%
#   group_by(Ecoregion) %>%
#   mutate(
#     ElevationBin = cut(
#       Elevation, 
#       breaks = seq(min(Elevation), max(Elevation), length.out = 11), include.lowest = TRUE))

# this binning method works but sometimes gives 11 bins instead of 10 
OBA_reprojected_df <- OBA_reprojected_df %>%
  group_by(Ecoregion) %>%
  mutate(
    ElevationBin = cut(
      Elevation, 
      breaks = 10,
      include.lowest = TRUE))

OBA_reprojected_df
unique(OBA_reprojected_df$Ecoregion)



table(unique(OBA_reprojected_df$Ecoregion))
 

```


