---
title: "Untitled"
output: html_document
date: "2024-11-13"
---

```{r setup, include=FALSE}
# packages that will be used
library(sf)
library(terra) 
library(ggplot2)
library(dplyr)
library(ggspatial)
#library(tmap)
library(RColorBrewer)

```


```{r, loading in Rdata}

#setwd("~/Desktop/beeproject")
#load("~/Desktop/beeproject/dem_rast_downsampled.RData")
class(dem_rast_downsampled)
str(dem_rast_downsampled)

# Print metadata
print(dem_rast_downsampled)
extent(dem_rast_downsampled)      # Get spatial extent
crs(dem_rast_downsampled)         # Get the coordinate reference system
res(dem_rast_downsampled)         # Get resolution

# Plot the DEM
plot(dem_rast_downsampled, main = "Digital Elevation Model")


```



```{r - Random stuff that may be useful later}
#gdb_file <- "C:/Users/Admin/Downloads/OR_DEM_10M.gdb/OR_DEM_10M.gdb/a00000029.gdbtable"
#layers <- st_layers(gdb_file)
#print(layers)

#gdb_data <- st_read(dsn = gdb_file, layer = "fras_blk_DEM_10meter_Oregon")


#head(gdb_data)

# commented code below is for cropping the extent of the data, will show a smaller portion of the state rather than a reduced res version

#extent <- ext(dem_rast) * 0.01  # Crop to 1% of the original size
#dem_rast_subset <- crop(dem_rast, extent)

# Convert the subset to a data frame
#dem_rast_df <- as.data.frame(dem_rast_subset, xy = TRUE)
#dem_rast_df <- as.data.frame(dem_rast, xy = TRUE)
#dem_rast_df

#gdb_path <- "C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb"
#raster <- rast("C:/Users/Admin/Downloads/OR_DEM_10M_files.gdb")
#raster
#layers <- terra::sources(gdb_path)
```





```{r - Code for reading in a reducing resolution of DEM data}

describe("~/Downloads/dem_rast_r.tif")
dem_rast <- rast("~/Downloads/dem_rast_r.tif")
crs(dem_rast)

dem_rast_downsampled <- aggregate(dem_rast, fact = 100, fun = mean)
dem_rast_dsamp_df <- as.data.frame(dem_rast_downsampled, xy = TRUE)
head(dem_rast_dsamp_df)
summary(values(dem_rast_downsampled))
plot(dem_rast_downsampled)

```




```{r Reading in ecoregion data and plot of elevation and ecoregions}

ecoregions_vec <- st_read("~/Downloads/5-OR-fires/OR-ecoregions")
head(ecoregions_vec)
class(ecoregions_vec)
#st_crs(dem_rast_downsampled)
class(dem_rast_downsampled)

#st_crs(dem_rast_downsampled)
#st_crs(ecoregions_vec)
ecoregions <- st_transform(ecoregions_vec, crs(dem_rast_downsampled), res=res(dem_rast_downsampled))
#st_crs(ecoregions)
head(ecoregions)
elevation_crop <- crop(x = dem_rast_downsampled, y = ecoregions)
elevation_crop_df <- as.data.frame(elevation_crop, xy= TRUE)

elevation_all_ecoregions_plot <- ggplot() +
  geom_raster(data = dem_rast_dsamp_df, aes(x = x, y = y, fill = OR_DEM_10M_files)) +
  scale_fill_gradientn(colours = terrain.colors(7)) +
  geom_sf(data = ecoregions, color = "black", fill = NA) 

elevation_all_ecoregions_plot

```
```{r Stuff for matching extent - doesn't work correctly}

# trying to crop the extent of the raster data so that it fits completely into the ecoregions data, but 
## neither of the below seem to work

#ecoregions_vec <- st_crop(ecoregions_vec, st_bbox(dem_rast_downsampled))
#dem_rast_downsampled <- crop(dem_rast_downsampled, st_bbox(ecoregions_vec))

# commented code below is something I found online for matching the extents of both data sets, results are weird

# names(ecoregions_vec)
crs(dem_rast_downsampled, proj = TRUE)
crs(ecoregions_vec, proj = TRUE)
# ext(dem_rast_downsampled)
# ext(ecoregions_vec)
# 
# aligned_raster <- resample(dem_rast_downsampled, rast(ecoregions_vec), method = "bilinear") 
# 
# ext(aligned_raster)

#align_dem_rast_df <- as.data.frame(aligned_raster, xy = TRUE)
#align_dem_rast_df

#elevation_all_ecoregions_plot <- ggplot() +
  #geom_raster(data = align_dem_rast_df, aes(x = x, y = y, fill = OR_DEM_10M_files)) +
  #scale_fill_gradientn(colours = terrain.colors(7)) +
  #geom_sf(data = ecoregions_vec, color = "black", fill = NA) 

#elevation_all_ecoregions_plot

```


```{r Splitting the ecoregions data into the separate ecoregions with elevation data}

# names(ecoregions_vec)
# crs(dem_rast_downsampled, proj = TRUE)
# crs(ecoregions_vec, proj = TRUE)
# ext(dem_rast_downsampled)
# ext
ecoregions_vec
minmax(dem_rast_downsampled)
st_crs(elevation_crop)
st_crs(ecoregions)

```

```{r Elevation data for east cascades}

east_cascades <- ecoregions %>% filter(Ecoregion == "East Cascades")
print(east_cascades)

Ecas <- terra::extract(x = dem_rast_downsampled, y = east_cascades, raw = FALSE)
print(Ecas)

plot(st_geometry(ecoregions), col = "lightgrey", main = "East Cascades Ecoregion Highlighted")
plot(st_geometry(east_cascades), col = "blue", add = TRUE)

ggplot() +
  geom_histogram(data = Ecas, aes(x = OR_DEM_10M_files))

```



```{r Elevation data for Klamath Mountains}

klamath_mt <- ecoregions %>% filter(Ecoregion == "Klamath Mountains")
print(klamath_mt)

Kmt <- extract(x = dem_rast_downsampled, y = klamath_mt, raw = FALSE)
print(Ecas)

plot(st_geometry(ecoregions), col = "lightgrey", main = "Klamath Mountains Ecoregion Highlighted")
plot(st_geometry(klamath_mt), col = "blue", add = TRUE)

ggplot() +
  geom_histogram(data = Kmt, aes(x = OR_DEM_10M_files))




```



```{r,reading in bee data and selecting OBA columns}

OBA <- read.csv("~/Downloads/6_OBA_spatial/OBA_2018-2023.csv")
head(OBA)


OBA <- OBA %>% 
  select("Location", "Dec..Lat." , "Dec..Long.", "Associated.plant" , "Genus", "Species", "sex") %>%
  rename(Latitude = Dec..Lat., Longitude = Dec..Long.)

head(OBA)


```



```{r, getting rid of na values and cleaning longitdue and converting to sf}

# sum(!is.na(OBA$Longitude))        # Count rows where Longitude is not NA
# sum(!is.na(OBA$Latitude))         # Count rows where Latitude is not NA
# sum(OBA$Longitude > -130)         # Count rows where Longitude > -125
# sum(OBA$Longitude < -116)         # Count rows where Longitude < -116
# 
# summary(OBA$Longitude)
# sum(is.na(OBA$Longitude))

#checking rows
# OBA_non_na <- OBA %>%
#   filter(!is.na(Longitude) & !is.na(Latitude))
# nrow(OBA_non_na)
# 
OBA_in_range <- OBA %>%
   filter(Longitude > -130 & Longitude < -116)
nrow(OBA_in_range)

#changing to numberic
OBA$Longitude <- as.numeric(as.character(OBA$Longitude))

OBA_clean <- OBA %>%
  filter(!is.na(Longitude) & !is.na(Latitude)) %>%
  filter(Longitude > -130 & Longitude < -116)

head(OBA_clean)


#filter(Longitude != 176.015)

# unique(OBA_clean$Longitude)
# 
# longitude <- c(OBA_clean$Longitude)
# longitude
# filtered_longitude1 <- longitude[longitude < -130]
# filtered_longitude1
# 
# filtered_longitude2 <- longitude[longitude > -116]
# filtered_longitude2


```


```{r, getting rid of na values and cleaning latitdue}

summary(OBA$Latitude)
sum(is.na(OBA$Latitude))

sum(!is.na(OBA$Latitude))        # Count rows where Longitude is not NA
sum(!is.na(OBA$Latitude))         # Count rows where Latitude is not NA
sum(OBA$Latitude > -47)         # Count rows where Longitude > -125
sum(OBA$Latitude < 43)

#checking rows
OBA_non_na <- OBA %>%
   filter(!is.na(Longitude) & !is.na(Latitude))
 nrow(OBA_non_na)

OBA_in_range <- OBA %>%
   filter(Latitude > 47 & Latitude < -43)
 nrow(OBA_in_range) 
 
#changing to numberic
OBA$Latitude <- as.numeric(as.character(OBA$Latitude))
 
OBA_clean <- OBA %>%
  filter(!is.na(Longitude) & !is.na(Latitude)) %>%
  filter(Longitude > -130 & Longitude < -116 & Latitude > -47 & Latitude < 47)

head(OBA_clean)

```




```{r, converting to sf}

OBA_sf <- st_as_sf(OBA_clean,
                          coords = c("Longitude","Latitude"),
                          crs = crs("EPSG:4326"))
head(OBA_sf)

OBA_sf

```








```{r, plotting OBA data}

#crs(ecoregions_OR, proj=TRUE)
#crs(OBA_sf)
#crs(dem_rast_downsampled, proj = TRUE)

crs("EPSG:4326")

# current_bbox <- st_bbox(bee_species_sp)
# print(current_bbox)
# 
# # Defining a new bounding box
# new_bbox <- st_bbox(c(xmin = -123.414, ymin = 41.998, xmax = -117.227, ymax = 45.868), crs = st_crs(bee_species_sp))
# 
# # Cropping to the new bounding box
# bee_data_cropped <- st_crop(bee_species_sp, new_bbox)
# 
# print(st_bbox(bee_data_cropped))

#mapping bee data
ggplot() +
  geom_sf(data = OBA_sf)
```


```{r}

ext(ecoregions_vec)
ext(bee_data_cropped)
ext(dem_rast)

crs(ecoregions_vec)
crs(bee_data_cropped)
crs(dem_rast)


bee_data_reprojected <- st_transform(bee_data_cropped, crs = 2992)

# DEM extent as SpatExtent
dem_extent <- ext(dem_rast_downsampled)

# Convert SpatExtent to an sf polygon
dem_extent_sf <- st_as_sf(as.polygons(dem_extent, crs = crs(dem_rast_downsampled)))

# Ensure the bee data and DEM extent are in the same CRS
bee_data_cropped <- st_transform(bee_data_cropped, crs(dem_extent_sf))

bee_data_clipped <- st_intersection(bee_data_cropped, dem_extent_sf)


ggplot() +
  geom_raster(data = dem_rast_dsamp_df, aes(x = x, y = y, fill = OR_DEM_10M_files)) +
  scale_fill_gradientn(colours = terrain.colors(7)) +
  geom_sf(data = ecoregions, color = "black", fill = NA) +
  geom_sf(data = OBA_sf)

```


```{r}

#or <- map_data("county", "oregon") %>% 
  #select(lon = long, lat, group, id = subregion)

# ggplot() +
#   geom_polygon(data = or, aes(x = lon, y = lat, group=group)) +
#   geom_sf(data = OBA_sf)


#OBA_sf <- st_transform(OBA_sf, st_crs(dem_rast_dsamp_df))  # Match CRS of ecoregions
#ecoregions <- st_transform(ecoregions_vec, crs(dem_rast_downsampled), res=res(dem_rast_downsampled))


OBA_sf <- st_transform(OBA_sf, crs(dem_rast_downsampled), res=res(dem_rast_downsampled))

ggplot() +
  geom_raster(data = dem_rast_dsamp_df, aes(x = x, y = y, fill = OR_DEM_10M_files)) +
  scale_fill_gradientn(colours = terrain.colors(7)) +
  geom_sf(data = bee_data_cropped) +
  scale_color_manual(values = "red", name = "Legend")
  geom_sf(data = ecoregions, color = "black", fill = NA)

```



